services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=es-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elknet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elknet

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms2g -Xmx2g
      - PIPELINE_WORKERS=3    # Ограничить воркеры
      - PIPELINE_BATCH_SIZE=1 # Минимальный batch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/data:/data
      - ./logstash/logs:/logs
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elknet

  ml-api:
    build:
      context: ./ml-api
      dockerfile: Dockerfile
    container_name: ml-api
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - elknet

volumes:
  es-data:
    driver: local

networks:
  elknet:
    driver: bridge
